version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./product_scraper/migrations:/docker-entrypoint-initdb.d

#  scraper:
#    build: .
#    depends_on:
#      - postgres
#    environment:
#      DB_NAME: ${DB_NAME}
#      DB_USER: ${DB_USER}
#      DB_PASSWORD: ${DB_PASSWORD}
#      DB_HOST: postgres
#      DB_PORT: 5432
#    command: ["python", "main.py"]

volumes:
  pgdata:
